ARCLawyerNetworkApp/Lawyer_Network/models.py
from ARCLawyerNetworkApp import db


serves = db.Table('serves',
    db.Column('lawfirm_id', db.Integer, db.ForeignKey('lawfirms.lawfirm_id')),
    db.Column('state_id', db.Integer, db.ForeignKey('states.states_id'))
    )

class Lawfirms(db.Model):
    lawfirm_id = db.Column(db.Integer, primary_key=True)
    lawFirmName = db.Column(db.Text)
    state = db.Column(db.Text)
    website = db.Column(db.Text)
    specialities = db.Column(db.Text)
    email = db.Column(db.Text)
    contactLink = db.Column(db.Text)
    genPhone = db.Column(db.Text)
    phone = db.Column(db.Text)
    address = db.Column(db.Text)
    #accountEmail = db.Column(db.Text)
    #notes = db.Column(db.Text)
    #password = db.Column(db.Text)


    serves = db.relationship('States', secondary=serves, backref= db.backref('statesServed', lazy = 'dynamic') )
    #accountEmail, password, probono, notes
    def __init__(self, lawFirmName, state, website, specialities, email, contactLink, genPhone, phone, address ):
        self.lawFirmName = lawFirmName
        self.state = state
        self.website = website
        self.specialities = specialities
        self.email = email
        self.contactLink = contactLink
        self.genPhone = genPhone
        self.phone = phone
        self.address = address
        #self.accountEmail = accountEmail    
        #self.password = generate_password_hash(password)  
        #self.notes = notes


    def __repr__(self):
        return f"The lawfirm name is {self.lawFirmName}"

class States(db.Model):
    states_id = db.Column(db.Integer, primary_key=True)
    states = db.Column(db.String(20))

    def __init__(self, states):
        self.states = states

    

    def __repr__(self):
        return f"The state is {self.states}"    

ARCLawyerNetworkApp/Lawyer_Network/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField,IntegerField,SubmitField,PasswordField,validators,SelectField)
from wtforms.validators import DataRequired,Email,EqualTo

class Search(FlaskForm):
	state = SelectField('State', validators = [DataRequired()], choices = ["Select State",'Arizona','California','Florida','Georgia'])
	submit = SubmitField('Sign Up')

	def validate(self): #this is the method that validates the form
		rv = FlaskForm.validate(self) #checks if the data was input

		if not rv:
			return False
		else:	 #validation didnt pass 
			return True

ARCLawyerNetworkApp/Lawyer_Network/views.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for
from ARCLawyerNetworkApp.Lawyer_Network.models import Lawfirms, States
from ARCLawyerNetworkApp import db,app

from ARCLawyerNetworkApp.Lawyer_Network.forms import Search

Lawyer_Network_app = Blueprint('Lawyer_Network', __name__)

@Lawyer_Network_app.route('/')
def index():
	return render_template('home.html')
	
@Lawyer_Network_app.route('/directory', methods= ['GET','POST'])
def directory():

	currentstate = States.query.get(3)
	if request.method == 'POST':
		lfsearch = request.form["lawfirm"]
		ssearch = request.form["state"]
		statesearch = States.query.filter_by(states= ssearch).first().statesServed

		return render_template('directory.html', statesearch=statesearch)	

	return render_template('directory.html')

@Lawyer_Network_app.route('/about')
def about():
	return render_template('about.html')
#creates endpoint for the About webpage 

@Lawyer_Network_app.route('/lawyer-profile/<lawfirm_id>', methods= ['GET','POST'])

def lprofile(lawfirm_id):
	
	currentlawfirm = Lawfirms.query.filter_by(lawfirm_id= lawfirm_id).first()
	return render_template('lawyer-profile.html', result=currentlawfirm)
	return f"{lfsearch} {ssearch}"

@Lawyer_Network_app.route('/claim-profile')
def claim():
	return render_template('claim-profile.html')


@Lawyer_Network_app.route('/results')
def results():
	return render_template('results.html')

ARCLawyerNetworkApp/Users/views.py
from flask import Flask, Blueprint, render_template, request, redirect
from flask import url_for, flash,abort,request,send_from_directory,session
import os
from ARCLawyerNetworkApp import db,app
from ARCLawyerNetworkApp.Users.createProfileForm import AddLawyer
from ARCLawyerNetworkApp.Users.LawyerLogin import LoginForm	
from werkzeug.security import generate_password_hash, check_password_hash
#from flask_login import login_user,login_required,logout_user
#from flask_login import LoginManager

Users_app = Blueprint('Users', __name__)
app.config['SECRET_KEY'] = 'mysecretkey'

#@login_manager.user_loader
#def load_user(user_id):
 #   return User.get(user_id)
'''
@app.route("/favicon.ico")
def favicon():
    return send_from_directory(os.path.join(app.root_path, 'static'),
                               'favicon.ico', mimetype='image/vnd.microsoft.icon')

'''
@Users_app.route('/login', methods= ['GET','POST'])
def login():
	form = LoginForm()
	if form.validate_on_submit():
		user = Lawfirms.query.filter_by(accountEmail=form.email.data).first()
		
		#if user.check_password(form.password.data) and user is not None:
		#	login_user(user)
		#	flash('Logged in successfully.')
		#	next = request.args.get('next')
		#	if next == None or not next[0]=='/':
		#		next = url_for('lawyer-profile')
		#		return redirect(next)
		session['id'] = user.lawfirm_id
		return redirect(url_for('Lawyer_Network.lawyer-profile'))
	return render_template('login.html', form=form)

@Users_app.route('/create-profile', methods= ['GET','POST'])
def create():
	form = AddLawyer()

	if form.validate_on_submit():
		lawfirmName = form.lawfirmName.data
		state = form.state.data
		website = form.website.data
		specialities = form.specialities.data
		email = form.email.data
		genPhone = form.genPhone.data
		address = form.address.data
		probono = form.probono.data
		accountEmail = form.accountEmail.data
		password = generate_password_hash(form.password.data) 
		notes = form.notes.data

		new_lawyer = Lawyer(lawfirmName, state, website, specialities, email, genPhone, address, probono, accountEmail, password, notes)   
		db.session.add(new_lawyer)
		db.session.commit()

		return redirect(url_for('lawyer-profile'))	

	return render_template('create-profile.html', form = form)
#creates endpoint for the register webpage 

@Users_app.route('/review-lawyer')
def review():
	return render_template('review-lawyer.html', methods= ['GET','POST'])

ARCLawyerNetworkApp/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
#from flask_login import LoginManager
from sassutils.wsgi import SassMiddleware

app = Flask(__name__)

app.config['SEND_FILE_MAX_AGE_DEFAULT'] = -1

basedir = os.path.abspath(os.path.dirname(__file__))

app = Flask(__name__,template_folder='./templates',static_folder='./static')

app.wsgi_app = SassMiddleware(app.wsgi_app,{'ARCLawyerNetworkApp':("static/styles", "static/styles", "/static/styles")})

app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:emily@localhost/ARCdb'
#app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:nurudeen@localhost/ARCdb'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)

Migrate(app,db)

from ARCLawyerNetworkApp.Users.views import Users_app
from ARCLawyerNetworkApp.Lawyer_Network.views import Lawyer_Network_app

app.register_blueprint(Users_app)
app.register_blueprint(Lawyer_Network_app)

#login_manager = LoginManager()
#login_manager.init_app(app)
#login_manager.login_view = "login"

ARCLawyerNetworkApp/templates/about.html
{%extends 'base.html' %}
{%block content%}

<div class="jumbotron big-banner2">

<h2>This Network was created for a Girl Scout Gold Award Project by Emily Simkovich of Troop 57087 in partnership with the Adoptee Rights Campaign.</h2>
<br>
<br>
<h2> The Adoptee Rights Campaign is a diverse group of advocates whose vision is full citizenship status for all intercountry adoptees. For more information please visit their website <a href="https://adopteerightscampaign.org/">adopteerightscampaign.org</a>. </h2>
<br>
<br>
<h2>To join the legal referral network please fill out the form <a href="{{ url_for('Users.create') }}">here</a>.</h2>
<br>
<br>
<h2>For inquries about the Lawyer Network, please email arc.legalreferralnetwork@gmail.com </h2>
<br>
<br>
<h2>For inquries about the Adoptee Rights Campaign, please email info@adopteerightscampaign.org</h2>
         
<img src="{{ url_for('static',filename='images/goldawardlogo.png') }}"width="150" height="150" alt="" loading="lazy">
<img src="{{ url_for('static',filename='images/gseplogo.png') }}"width="300" height="175" alt="" loading="lazy">
<img src="{{ url_for('static',filename='images/ARClogo.png') }}" loading="lazy">


</div>






{% endblock %}

ARCLawyerNetworkApp/templates/create-profile.html
{%extends 'base.html' %}
{%block content%}
<head>
	<link rel="stylesheet" href="{{ url_for('static', filename='styles/styles.css') }}">
		<script>
			function create_account() {
				const http = new XMLHttpRequest();
				const url = "http://127.0.0.1:5000/create";
				
				http.open("POST", url);
							
				http.onreadystatechange = function() {
					if(this.readyState==4) { // Make sure we have received a response
						var status = document.getElementById("create-status");
						if(this.status==201) { // Make sure the response is good.
							status.classList.add("success");
							status.classList.remove("failure");
							status.innerHTML = "Account successfully created.";
							setTimeout(function() {
								window.location.href = "http://127.0.0.1:5000/login";
								}, 1500);
						} else {
							status.classList.add("failure");
							status.classList.remove("success");
							if (this.status==409) {
								status.innerHTML = "Account already exists.";
							} else {
								status.innerHTML = "Something went wrong. Try again later.";
							}
						} 
						
					}
				}
				var formData = new formData();	
				formData.append("username", document.getElementById('username').value);
				formData.append("password", document.getElementById('password').value);
				http.send(formData);	
			}
		</script>
</head>
<div class="jumbotron big-banner">
	
	<h3 style="text-align:center;" class="card-title"><b>Join the Network</b></h3>
<form action="javascript:;" onsubmit="create_account()", method="POST">
<div class="wrapper">
  <div class="card wrapper" style="width: 35rem;">
    <div class="card-body">
      <form method="POST">
        <img class="center" src= "{{ url_for('static',filename='images/ARClogo.png') }}" width="90" height="70" alt="" loading="lazy">
        <br>	
	 
	  {# This hidden_tag is a CSRF security feature. #}
      {{ form.hidden_tag() }}

      {{ form.lawfirm.label}} 
      {{ form.lawfirm(class= "form-control") }}

      {{ form.states.label }} 
      {{ form.states(class= "form-control") }}

      {{ form.website.label }} 
      {{ form.website(class= "form-control") }}

      {{ form.specialities.label }} 
      {{ form.specialities(class= "form-control") }}

      {{ form.email.label }} 
      {{ form.email(class= "form-control") }}

      {{ form.phone.label }} 
      {{ form.phone(class= "form-control") }}

      {{ form.address.label }} 
      {{ form.address(class= "form-control") }}

      {{ form.probono.label }} 
      {{ form.probono(class= "form-control") }}

      {{ form.accountEmail.label }} 
      {{ form.accountEmail(class= "form-control") }}      

      {{ form.password.label }} 
      {{ form.password(class= "form-control") }}

      {{ form.confirmPassword.label }} 
      {{ form.confirmPassword(class= "form-control") }}
      <br>
      {{ form.submit(class= "btn btn-primary") }}

    </div>
  </div>
</div>
      


		  <!--<label for="name">Law Firm Name:</label><br>
		  <input type="text" class="form-control"  id="name" aria-describedby="emailHelp" placeholder="Law Firm">
		  <br><br>

		  <label for="state">What states are you certified by the Bar to serve in?</label><br>
		  <input type="text" class="form-control"  id="state" placeholder="Ex: Ohio, New Jersey, etc"><br><br>

		  <label for="website">Firm's Website:</label><br>
		  <input type="text" class="form-control"  id="website" placeholder="www.lawfirm.com"><br><br>

		  <label for="specialities">What are your firm's immigration specialties?</label><br>
		  <input type="text" class="form-control" id="specialities" placeholder="Ex: deportation defense, citizenship, etc"><br><br>		 

		  <label for="email">What email should potential clients use to contact you?</label><br>
		  <input type="email" class="form-control" id="email" placeholder="lawfirm@lawfirm.com"><br><br>
		  

		  <label for="phone">What phone number should potential clients use to contact you?</label><br>
		  <input type="number" class="form-control" id="phone" placeholder="XXX-XXX-XXXX"><br><br>

		  <label for="address">What is your firm's main address?</label><br>
		  <input type="text" class="form-control"  id="address" placeholder="Address"><br><br>

		  <label for="address">Will your firm offer pro-bono or low-bono services?</label><br>
		  <div class="form-check">
  			<input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
  			<label class="form-check-label" for="exampleRadios1">
  				  Yes
 			 </label>
			</div>
			<div class="form-check">
			 			 <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
			  <label class="form-check-label" for="exampleRadios2">
			    No
			  </label>-->
			</form>
			</div>


 	<!--	<p>Does your firm have any additional addresses?</p>
		  <div class="form-check">
  <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
  <label class="form-check-label" for="exampleRadios1">
    Yes
  </label>
</div>
<div class="form-check">
  <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
  <label class="form-check-label" for="exampleRadios2">
    No
  </label>
</div>
<br>
		  <input type="submit" class="btn btn-primary" value="Submit">

		</form>
		<div id="create-status"></div>

</div>-->




{% endblock %}

ARCLawyerNetworkApp/templates/results.html
{%extends "base.html"%}
{%block content%}

{%for result in statesearch %}
<p>testy</p>
<p> {{result.lawFirmName}}</p>

{%endfor%}



{% endblock %}